// Code generated by MockGen. DO NOT EDIT.
// Source: internal/audit/audit.go
//
// Generated by this command:
//
//	mockgen -source=internal/audit/audit.go -destination=internal/audit/mock_audit.go -package=audit
//

// Package audit is a generated GoMock package.
package audit

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockObserver) Notify(event Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockObserverMockRecorder) Notify(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockObserver)(nil).Notify), event)
}
